name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    # https://github.com/actions/first-interaction
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Olá e boas vindas ao meu repo de teste! Hi and welcome to my test repo!"
        pr-message: "Olá e boas vindas ao meu repo de teste! Hi and welcome to my test repo!"
