name: "Dependent Jobs"

on: ['push']

jobs:  
    
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, "
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: World
        run: echo "World!"

