name: Workflow-Commands

on:
  push:
    branches:
      - main

jobs:
  workflow-commands:
    runs-on: ubuntu-latest

    steps:
    - name: group logging
      run: |
        echo "::group::Log_Grupo1"
        echo "Ola"
        echo "eu"
        echo "sou"
        echo "um"
        echo "grouping"
        echo "log"
        echo "::endgroup::"

    - name: set env vars
      run: echo "ACTION_ENV=main" >> $GITHUB_ENV

    - name: adicionar diretorio para PATH
      run: echo "/home/" >> $GITHUB_PATH

    - name: mensagem debug
      run: echo "::debug::MSG_DEBUG"

    - name: mascarar valor sensivel      
      run: |
      $MY_SECRETY="lasanha"      
      echo "::add-mask::$MY_SECRET"
      echo "O melhor prato do mundo é: $MY_SECRET"

    - name: Falha no workflow
      run: echo "::error::Erro no workflow"
